#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'nginx'
cookbook 'php'
cookbook 'rabbitmq'
cookbook 'mysql'
cookbook 'database'
cookbook 'git'
cookbook 'vim'
cookbook 'redis', :git => 'https://github.com/ubermuda/chef-redis.git'